mava/_metadata.py

Updated release information in `setup.py`. 
For release. 
-
-

fix: Updated versions in setup to match release.

---

examples/quickstart.ipynb

- Made quickstart notebook download latest mava from git. 
- Minor updates and fixes in examples. 
Notebook should be using new version of mava. 
-
[Any extra information.]

Chore/ Update quickstart

---

.github/workflows/ci.yaml
mava/adders/reverb/base.py
mava/adders/reverb/episode.py
mava/adders/reverb/sequence.py
mava/adders/reverb/transition.py
mava/adders/reverb/utils.py
mava/utils/loggers/tf_logger.py
mava/wrappers/environment_loop_wrappers.py
setup.py

Updates for `dm-acme` version 0.2.2. 
-
-
-

chore/Updates for new acme version.

---

mava/components/building/__init__.py
mava/components/building/setup.py
mava/systems/building.py
mava/systems/launcher.py
mava/systems/tf/maddpg_v2/building.py

Create a setup component to handle general building setup code.
This is to move some of the general setup code that does not have hooks, in the Launcher, to a component that has hooks.
Added a setup component [here](https://github.com/instadeepai/Mava/blob/feature/update_launcher/mava/components/building/setup.py) that handles general setup instructions.
.

Mava Redesign/Update Launcher

---

mava/__init__.py
mava/core.py
mava/environment_loop.py
mava/environment_loops/open_spiel_environment_loop.py
mava/systems/launcher.py
mava/wrappers/environment_loop_wrappers.py
tests/system.py

Fix minor bugs in Mava init code. The Launcher can now be called and works on both GPU/CPU.
To be able to call the Mava Launcher and use it in an external project.
Minor bug-fixes throughout the codebase.
.

Minor bug-fixing to get redesign Launcher running.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Simple bug and feature issue templates.

feat(git): Added feature and bug templates.

---

README.md

Update README to link to pypi package
Norm of other repos. More traffic to pypi
Update README to link to pypi package

Update README to link to pypi package

---

.github/CODEOWNERS

Expand code owner list
Have more default reviewers to improve code review
Add additional code owners names.
closes #389

chore: expand code owner list for better code review

---

examples/tf/quickstart.ipynb

Readd quick start notebook.
For some reason, it disappeared in the previous PR.

fix: readd quickstart notebook

---

mava/systems/tf/madqn/networks.py
mava/systems/tf/value_decomposition/networks.py

Remove redundant value_network code
Refactoring is important 
Remove redundant value_network code

Maintenance: Remove redundant value_network code

---

mava/_metadata.py

Version bump for new release. 
-
-
-

Feat/Release new mava version.

---

examples/README.md

Fix broken readme links and neaten up formatting
usable README
Fix broken readme links and neaten up formatting

Fix broken readme links and neaten up formatting

---

mava/_metadata.py

Feat/Upped pypi version. 

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
mava/wrappers/open_spiel.py
mava/wrappers/pettingzoo.py
pyproject.toml
setup.py

Upgrade the black package version.
The current version of black seems to be producing an error.
Updated the setup.py file.
.

fix: Update black version.

---

mava/_metadata.py

chore: Up the patch version of mava - 0.1.3.

---

mava/components/jax/building/adders.py
mava/components/jax/building/data_server.py
mava/components/jax/building/datasets.py
mava/components/jax/building/distributor.py
mava/components/jax/building/environments.py
mava/components/jax/building/loggers.py
mava/components/jax/building/networks.py
mava/components/jax/building/parameter_client.py
mava/components/jax/building/reverb_components.py
mava/components/jax/building/system_init.py
mava/components/jax/component.py
mava/components/jax/executing/action_selection.py
mava/components/jax/executing/base.py
mava/components/jax/executing/observing.py
mava/components/jax/training/advantage_estimation.py
mava/components/jax/training/base.py
mava/components/jax/training/losses.py
mava/components/jax/training/model_updating.py
mava/components/jax/training/step.py
mava/components/jax/training/trainer.py
mava/components/jax/updating/parameter_server.py
mava/components/jax/updating/terminators.py
tests/jax/mocks.py

Documented jax Mava components.
Jax mava systems need documentation.
Filled out docstrings and added comments.
Closes #648

docs: Documentation for Mava components

---

mava/systems/README.md

Fix autodocs not updating on website
Closes https://github.com/instadeepai/Mava/issues/694
Docs need to be accessable to users on [https://id-mava.readthedocs.io/en/latest/systems/general/]https://id-mava.readthedocs.io/en/latest/systems/general/
Updated JAX logo path to correct branch
Fix JAX Logo path

Fix: Docs not updating

---

examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo.py
examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_sep_networks.py
examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_with_monitoring.py
examples/jax/flatland/feedforward/decentralised/run_ippo.py
examples/jax/smac/feedforward/decentralised/run_ippo.py
examples/jax/smac/feedforward/decentralised/run_ippo_sep_networks.py
mava/components/jax/building/parameter_client.py
mava/specs.py
mava/systems/jax/ippo/system.py
tests/jax/components/building/networks_test.py
tests/jax/systems/systems_test_data.py

Make the separate networks ippo system build from the shared networks ippo.
This shows how components can be used to upgrade a system.
Changed the ippo system file.
The network sizes are now also updated to be an exponent of 2.
Close #707

Feature: Make separate networks ippo build from shared networks ippo.

---

.github/workflows/push_docker.yaml

Update to ci for docker to reflect new benchmarking labels. Added new labels to be more specific about benchmarking status:
* Benchmark required - needs benchmarking, but has not yet been set to run.
* Benchmark in progress - experiments have been kicked off and are still running.
* Benchmarking is complete - results are in.

update benchmarking labels

---

.github/CODEOWNERS

Update code owners list to reflect changes in the team.

Update codeowners list

---

mava/wrappers/smac.py

Fix the legal action issue in SMAC

fix: smac action selection bug 

---

mava/components/building/__init__.py
mava/components/building/extras_spec.py
mava/systems/ippo/components.py
tests/components/building/extras_spec_test.py

Made a general extras spec base componenent as opposed to the one that lived inside the IPPO folder, as it will be needed for most if not all systems
To increase code re-use
Moved the already existing class into the general components folder

feature: made a general extras spec component

---

.github/codecov.yml

- Minor config change for codecov.
- Prev settings were too strict. 
-
-

chore: Update codecov settings.

---

mava/core_jax.py
tests/core_system_components/core_jax_test.py

Added `core_component.has` method
Useful as a better alternative to `hasattr`
Made base class for core component and implemented it there by checking if the given component type is in the callbacks list
Closes: #845 
Required for: #852

feat: added `core_component.has` method

---

.gitignore
mava/configs/default.yaml
mava/evaluator.py
mava/logger.py
mava/systems/ff_ippo_rware.py
mava/systems/ff_mappo_rware.py
mava/systems/rec_ippo_rware.py
mava/systems/rec_mappo_rware.py
mava/types.py
mava/utils/logger_tools.py
mava/wrappers/jumanji.py
requirements/requirements.txt

Split the actor-critic network
Change the logic of agent id by editing the wrapper
Add the option of logging to Neptune
The split of actor-critic improves the performance.
This is joint work done with @RuanJohn

Feat: split actor-critic networks

---

mava/utils/logger_tools.py

Log timesteps to the x-axis on Neptune.
It makes plots on Neptune far easier to interpret and also allows for comparing sample efficiency across experiments that ran for different total numbers of timesteps.

feat: log environment timestep to x-axis on neptune

---

README.md

Basic/minor updates to the readme to point to our other libraries and related libraries.

docs: update see also

---

README.md

Small readme update to add TRC acknowledgements.

docs: add TRC ack
