instadeepai/Mava

.github/workflows/ci.yaml, .pre-commit-config.yaml, pyproject.toml, setup.py
Added `interogate` package to check and enforce docstring code coverage. 
Better quality code documentation. 
-
Currently, the pre-commits will fail if docstring code coverage is less than 54.4% (our current docstring coverage is 54.5%). This will prevent new code without docstrings from being committed and we can increase this percentage as we go along. @arnupretorius Sounds good?
=> Feature/Enforce docstring code coverage.

mava/utils/environments/render_utils.py, mava/utils/environments/smac_utils.py, mava/wrappers/smac.py, tests/systems/dial_system_test.py, tests/systems/mad4pg_system_test.py, tests/systems/maddpg_system_test.py, tests/systems/madqn_system_test.py, tests/systems/mappo_system_test.py, tests/systems/qmix_system_test.py, tests/systems/vdn_system_test.py
- Fix SC2 load errors. 
- Make system tests use one executor for more consistency. 
-
-
-
=> fix/ Smac Load

Dockerfile
[Describe what was changed and reference relevant issue.]
From Pull Request: https://github.com/instadeepai/Mava/pull/284
This modification related to the issue when install Docker for SMAC: #282
I tried to install Docker to both Python 3.6 and Python 3.7 and figure out that pysc2 needed as well as uninstall enum34 is needed before pip install oxwhiri/smac github repo to prevent enum-Python 3.6 error. Note that there are suggestion for update enum instead of uninstall but this will not work
[Describe why the change was made.]
To be able to install Docker on Python 3.6, 3.7 correctly
[Describe how the change was made i.e. describe technically what the change does.]
Shown below
[Any extra information.]
Also, I suggested to update the main Docker repo to up-to-date with the develop one since …
=> update Dockerfile for SMAC installation

mava/utils/debugging/scenarios/simple_spread.py
Fix a bug in the observation calculation for the debugging environment, as pointed out by @mlanas in #287. 
Bugfix.
Fixed a landmark calculation typo error in `utils/scenarios/simple_spread.py`.
=> Bugfix: Simple_spread observation code.

mava/utils/wrapper_utils.py, mava/wrappers/environment_loop_wrappers.py
Fix step loggers to only log at the end of the episode.
The per agent loggers are doing an unnecessary amount of computation and are more noise than they have to be for the reward logging. The logger charts also did not seem to align in time but this seems to now be fixed.
Update the per agent loggers to only write once at the end of each episode.
.
=> Fix per agent loggers

Dockerfile, setup.py
Fix an error where the building of Mava crashes when trying to build Flatland.
Fix a bug in the building of Mava.
Manually install the package `pyparsing` before installing Flatland.
.
=> Fix Flatland package error in Docker build

mava/wrappers/robocup.py
Update RoboCup to work with the latest Mava version.
The RoboCup example is currently broken. This small change fixes the example.
Update the state name that gets passed to the agents to the correct expected state name.
=> Fix RoboCup environment wrapper

README.md
Update the `pip install` command for installing dependencies from source
It did not include `#egg=id-mava[reverb,tf,launchpad]`
I just added it in.
=> Updated pip installation instructions in README

.github/ISSUE_TEMPLATE/benchmarking_internal.md
Issue template for benchmarking tasks.
To organise/plan benchmarking work.
Add markdown template.
closes #382
=> feat: benchmarking issue template

.pre-commit-config.yaml, CONTRIBUTING.md
Fix conventional commit pre-commit hook.
Invalid commit messages should be blocked at a commit level. 
-
Closes https://github.com/instadeepai/Mava/issues/394 .
=> Bugfix: Fixed conventional commit pre-commit hook not running.

.github/ISSUE_TEMPLATE/feature_internal.md, .github/ISSUE_TEMPLATE/test_internal.md
Issue template for testing.
Good for outlining and planning tests for features etc.
Add markdown file.
closes #386
=> feat: internal issue tempalte for tests

mava/wrappers/__init__.py
Fixes the bug where the smac wrapper won't be imported if flatland is not installed. 
- Run smac experiments without flatland being installed. 
- Two separate try catch statements. 
Closes https://github.com/instadeepai/Mava/issues/412 .
=> Fix/Smac Wrapper Relies on Flatland Installation

setup.py, tests/wrappers/wrapper_test.py
Fixes broken tests due to new gym version. 
- New gym version (0.22.0) breaks our tests. This is related to the output of wrapped_env.action_spaces[agent].sample() for pettingzoo.mpe.simple_spread_v2. Old version returns `{'agent_0': 3, 'agent_1': 3, 'agent_2': 3} `, new version returns `{'agent_0': 0, 'agent_1': 0, 'agent_2': 0}` - i.e. `no_action` resulting observations not being updated and thus the test fails.
Fix tests. 
Change seed and specify gym version so this doesn't happen in the future. 
Closes https://github.com/instadeepai/Mava/issues/420
=> fix: Fix broken tests due to new gym version. 

mava/systems/tf/madqn/execution.py, mava/wrappers/pettingzoo.py
The legal action mask in pettingzoo Pong was causing the madqn example to fail. This is because MADQN expects the legal action mask to be a vector of ones and zeros specifying for each action if it is a valid action or not. The pettingzoo wrapper was returning only a single one value for the legal action mask.
Also fixed problem in TicTacToe example. The MADQN executor needs a `select_action` method for single agents.
The MADQN example on Pong was failing.
Simple fix in the pettingzoo wrapper. 
MADQN needs `select_action` method for single agents in sequential games like Tic Tac Toe.
N/A
=> fix: small bug in the pettingzoo wrapper related to legal action masking

Dockerfile, setup.py
Fix version conflict between mava's gym version and flatland's gym version.
To be able to build the flatland container.
Use flatland's gym version (for now). 
Closes https://github.com/instadeepai/Mava/issues/436.
=> Fix/Flatland Docker Container

setup.py
Certain environments need to be updated for the new version of gym - e.g. debugging env. Currently, these envs + new version of gym = mypy issues.
-
-
Closes https://github.com/instadeepai/Mava/issues/455 .
=> Bugfix/Mypy Inconsistency Issue

.github/workflows/release.yaml, mava/systems/tf/mappo/networks.py, mava/utils/environments/open_spiel_utils.py, mava/utils/environments/pettingzoo_utils.py, mava/utils/wrapper_utils.py, mava/wrappers/env_preprocess_wrappers.py, mava/wrappers/environment_loop_wrappers.py
Changed pypi job to be triggered whenever a release is `published` and not just `created`. For some reason, currently it appears that github thinks release 0.1.2 has ready been created and hence won't trigger the pypi job. Changing this to work on whenever a release is `released` seems better practice (https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release , https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release). 
Release aren't triggering pypi push job.
-
Seems related to this https://github.com/actions/starter-workflows/issues/554 .
=> Bugfix/ Release aren't triggering pypi push job.

mava/components/jax/building/adders.py, mava/components/jax/building/adders_test.py, mava/components/jax/building/data_server.py, mava/components/jax/building/datasets.py, mava/components/jax/building/distributor.py, mava/components/jax/building/environments.py, mava/components/jax/building/loggers.py, mava/components/jax/building/networks.py, mava/components/jax/building/parameter_client.py, mava/components/jax/component.py, mava/components/jax/executing/action_selection.py, mava/components/jax/executing/base.py, mava/components/jax/executing/observing.py, mava/components/jax/training/advantage_estimation.py, mava/components/jax/training/base.py, mava/components/jax/training/losses.py, mava/components/jax/training/model_updating.py, mava/components/jax/training/step.py, mava/components/jax/training/trainer.py, mava/components/jax/updating/parameter_server.py, mava/systems/jax/config.py, mava/systems/jax/mappo/components.py, mava/systems/jax/system.py, mava/systems/jax/system_test.py, mava/testing/building/mocks.py
Ensure components are only initialized once. 
Component init could be computationally expensive and so it should only be done when necessary.
Made `name` and `config_class` static methods so that they can be accessed without initializing the components. 
@arnupretorius @DriesSmit Similiar to what we discussed earlier today.
=> Feature/Only init component once.

examples/tf/debugging/simple_spread/feedforward/decentralised/run_maddpg_scale_trainers_fixed_nets.py, mava/systems/tf/mad4pg/execution.py, mava/systems/tf/mad4pg/system.py, mava/systems/tf/maddpg/builder.py, mava/systems/tf/maddpg/execution.py, mava/systems/tf/maddpg/system.py, mava/utils/sort_utils.py
Add the capability to fix the sampler for MADDPG/MAD4PG. Also implemented bug fixes with @EdanToledo and @sash-a to get agents with different network architectures working in Mava.
@EdanToledo and @sash-a would like the feature of having fixed networks for each agent, while each trainer only trains on one network.
Added a `fix_sampler` variable to the MADDPG/MAD4PG systems that allow a user to create a fixed sampling order for the agent networks.
@sash-a and @EdanToledo please take a look at the new example and see if this would work for you?
=> feat: Add fixed sampler capability + bugfixes

mava/components/jax/building/datasets.py, mava/components/jax/training/model_updating.py, mava/components/jax/training/step.py, mava/systems/jax/parameter_client.py
Fix two bugs found by @EdanToledo. 
1.) Fix a small variable scope issue in the JAX parameter client.
2.) Fix a bug where the epoch batch_size argument is configurable. This variable should not be specified but inferred from the sequence length and the TrajectoryDataset batch size.
Bugfixes.
Made changes to the parameter client and MAPGEpochUpdate component.
=> fix: Fix parameter_client and batch_size in trainer component.

mava/systems/jax/builder.py, mava/systems/jax/executor.py
Changed name of parameter in the executor store
`config` is a confusing parameter name, especially when looking at the executor creation in the builder where it was
```python
self.store.executor = Executor(
config=self.store,
components=self.callbacks,
)
```
Personally was getting confused thinking it wanted a config class and not the store.
=> fix: changed confusing Executor parameter name

mava/components/jax/executing/action_selection.py
Closes #494
Removed implicit obs flattening from executor's action selection. It should rather be done by the networks
Changed `action_selection.py` to not flatten observations before passing them to the neural network and instead unsqueeze them.
Because the current behavior is undesirable for grid world style environments where agents can benefit from spatial knowledge
The change simply adds a batch dimension without flattening the observations
=> fix: removed obs flattening from executor's action selection

mava/components/jax/building/networks.py
Removed storing of shared weights config in the store
- No reason for having `shared_weights` in the store. Not used anywhere in systems
- Global config means all components will have access to it anyway, if needed
Remove code that fetches `shared_weights` from the config and loads it into the store
=> fix: remove redundant storing of shared weights config in store

tests/jax/components/building/loggers_test.py, tests/jax/mocks.py
Unit tests for jax logging components
Component currently not tested. Needs to be robust for jax Mava release
- Test `Logger` component
- Fixed typo in `mocks.py`
Closes #525
=> test: unit tests for jax logging components

mava/systems/jax/builder.py, mava/systems/jax/parameter_server.py, mava/systems/jax/trainer.py, tests/jax/components/training/advantage_estimation_test.py, tests/jax/core_system_components/parameter_server_test.py
Small PR to rename `config` to `store` in `__init__` methods of `ParameterServer` and `Trainer`.
`Config` is not the correct name for what was being passed through.
Renamed args and references.
Tested on `run_mappo` and all jax tests.
=> refactor: rename trainer and param server init config to store

examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py, mava/components/jax/building/distributor.py, mava/systems/jax/launcher.py, tests/jax/integration/mock_systems.py, tests/jax/integration/trainer_test.py
Remove the multi-threading option from the distributor and launcher.
The multi-threading option is unnecesary and complicates our testing process.
Remove the multi-threading option from the distributor and launcher code.
Close #690
=> Feature: Remove multi-threading

examples/jax/debugging/simple_spread/feedforward/decentralised/run_mappo_pretained.py, mava/components/jax/updating/parameter_server.py
Updated the param server for JAX functionality
Useful to load pretrained weights. JAX required additional variables to be added to the server
Updated the param server to load pre-trained weights. Added JAX seed and optax state to param server (and client)
We are still using ACME JAX Chekcpointer. Longer term we can remove this dependency
=> Update JAX Checkpointing/ Param Server

examples/jax/quickstart.ipynb
Fix the JAX quickstart notebook by setting the GPU memory preallocation to false. Thanks @RuanJohn for the suggestion :slightly_smiling_face: 
The trainer runs out of GPU memory and crashes.
Updated the JAX notebook file.
=> Fix JAX quickstart notebook

mava/components/jax/building/parameter_client.py, mava/components/jax/executing/action_selection.py, mava/components/jax/training/losses.py, mava/components/jax/training/step.py, mava/components/jax/training/trainer.py, mava/components/jax/updating/parameter_server.py, mava/systems/jax/ippo/networks.py, tests/jax/components/building/parameter_client_test.py, tests/jax/components/executing/action_selection_test.py, tests/jax/components/training/losses_test.py, tests/jax/components/training/model_updating_test.py, tests/jax/components/training/step_test.py, tests/jax/components/training/trainer_test.py, tests/jax/components/updating/parameter_server_test.py, tests/jax/core_system_components/parameter_client_test.py, tests/jax/integration/parameter_server_test.py, tests/jax/integration/trainer_test.py
Remove redundant networks dict (as carried over from TF)
Code is more readable and easier to follow
Remove redundant networks dict from `mava/systems/jax/ippo/networks.py`
The different types of networks are now handled in the networks class (PPONetworks) and hence we can remove the dict, that served this purpose in TF
Close https://github.com/instadeepai/Mava/issues/748
=> Maintain: Remove redundant networks dict

mava/systems/jax/launcher.py
Update the trainer name in the single process launcher. The old name does not exist anymore and crashes the code.
Bugfix.
Update the trainer name in the single process launcher. 
Close #766
=> Fix: Single process launcher

setup.py
Pin the version of jaxlib
Checks are failing because of this error
`jaxlib version 0.3.20 is newer than and incompatible with jax version 0.3.15. Please update your jax and/or jaxlib packages.`
=> fix: pin the version of jaxlib (checks are failing)

setup.py
Set importlib packange version < 5.0.
The latest version of importlib breaks the Python 3.7 checker.
Set importlib package version to be less than 5.0 in setup.py.
=> fix: Python 3.7 checker issue.

bash_scripts/tests.sh
Fix broken code coverage. Seems to be related to a certification issue which I suspect comes from the integrity check
Remove integrity checks. We can look at adding these in later again since the issue is likely on codecov's side.
=> fix: remove integrity check

examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py, mava/components/training/losses.py, mava/components/training/step.py, mava/utils/jax_training_utils.py
Fixed bug with target value normalisation when clip_value is True
The behaviour values are de-normalised in order to computed the advantages. To implement clip value, the new crtic values need to be compared with the old behaviour values but these were de-normalised.
Normalised the de-normalised behaviour values before sending it to the critic loss function.
Closes #811 
[Benchmarking results. ](https://www.notion.so/Test-value-normalisation-bugfix-393d5f74562c4e43a36eb5dd70cd3a89)
=> fixed bug with target value normalisation when value clip is true

mava/wrappers/env_preprocess_wrappers.py
Added a minor fix in the environment pre-process wrappers that allows them to accept environments that do not provided a dictionary for extra specifications. 
- The step and reset functions were slightly modified to return an empty dictionary if none is provided.
- Allows the ability to use concat wrappers on pettingzoo environments.
=> Bugfix: environment concatenation wrappers

DETAILED_INSTALL.md, mava/adders/reverb/base.py, mava/components/updating/terminators.py, mava/environment_loop.py, mava/systems/trainer.py
- This PR updates the environment loop print statements.
- It also updates the code to avoid shuffling of agent observations in the trainer.
- The new catch statement in the environment loop prevents Launchpad from printing when using Docker.
- While the agent observation issue was not specifically a bug, it does lead to confusion when using a single trainer. This has now been fixed.
- This code adds a sort statement in the base adder.
- It also changes the prints in the environment loop to tf.print.
.
=> fix: Agent id observation mismatch

mava/systems/ippo/networks.py
- Optional MLP layer on hidden features after recurrent layers is never called.
- The optional mlp layer was created but never appended to the policy network list.
- Appended the mlp layer to the network list.
- Add an if statement to check if the len of the recurrent layers is > 0.
=> fix: bug optional MLP layer after recurrent layer is never called

Dockerfile
Pin the version of `jax cuda` in the Dockerfile to match the version in the setup file.  
There was a breaking change in the `jax` and `jaxlib` `0.3.25` release leading to the following error: 
`AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'`. If the version is only pinned in the setup file the wrong version will still be pushed to Dockerhub and included in the Docker builds. 
Pinned the version in the Dockerfile. 
Link to the [same issue experienced](https://github.com/deepmind/dm-haiku/issues/565) by others on the Haiku repo.
=> fix: pin jax cuda version in dockerfile to match version in setup file.

examples/quickstart.ipynb, setup.py
Updated the *Installing Packages* code block due to minor issues with Colab.
Trying to run the Quickstart example on Colab faced two issues:
1. Sometimes when trying to install `box-2d`, a package called `swig` must first be installed—it seems to be a fairly common problem (for [example](https://stackoverflow.com/questions/54252800/python-cant-install-box2d-swig-exe-failed-with-error-code-1))
2. Intermittently, Colab also vaguely complained about numpy: 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```
- `!apt-get install swig` installs swig before trying to install Mava, which allows `box-2d` …
=> fix: import of required packages in quickstart to run on Colab.

mava/utils/loggers/base.py, mypy.ini, tests/components/building/loggers_test.py, tests/wrappers/wrapper_test.py
- Support tensorboard logs to s3 url.
- So we use s3 urls for tb logs. 
- Don't parse s3 urls and add `import tensorflow_io`. 
-
=> feat: Add s3 support to tensorboard logging.

mava/configs/default.yaml, mava/logger.py, mava/systems/ff_ippo_rware.py, mava/systems/ff_mappo_rware.py, mava/systems/rec_ippo_rware.py, mava/systems/rec_mappo_rware.py, mava/utils/logger_tools.py
Previously sacred logs and tensorboard were getting stored in different directories due to using `os.path.dirname` at different levels in the `mava` directory. This PR standardises storing logs in the base directory and enables for a unified `base_exp_path` to be passed to both the tensorboard and sacred loggers. This has further benefits for future running on the internal cluster.
=> feat: changed logging path

mava/utils/logger_tools.py
Small fix that sets Neptune parameters correctly again. 
The way we set the experiment parameters was changed from `self._run["params"] = self._exp_params` -> `self._run.params = self._exp_params`, but this does not log the experiment params on Neptune. This PR just changes it back to how it was before.
=> fix: fix experiment parameters not being set in neptune

mava/wrappers/jumanji.py
Fixing the shape of global observation in the case of centralised training and no agent id.
Duplicate the global obs for each agent as we vmap over the full observation
=> Fix: fixing global-obs shape in case of no agent-id 

requirements/requirements.txt
Unpin the jax version
It would be nice to always use the most recent jax
Change the requirements.txt, had to also switch to distrax master, see https://github.com/google-deepmind/distrax/issues/249
=> chore: unpin jax version

README.md, mava/configs/arch/anakin.yaml
Adds a simple example in the README for how to run a Mava system. 
Sets the default number of environments to 16 so that systems can be run on any hardware out of the box.
=> feat: update readme with simple instructions for running systems
